#test
name: continious deploy
on: workflow_dispatch
    


env:
    APPLICATION_NAME: "az-tf-1001"
    ENVIRONMENT_NAME: "dev"
jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:
              - uses: actions/checkout@v2

              
              - name: TF Setup
                uses: hashicorp/setup-terraform@v3
                with:
                  terraform_version: '1.9.2'
                  terraform_wrapper: false
            
              - name: Initialize Terraform
                env:
                  ARM_SUBSCRIPTION_ID: ${{ var.ARM_SUBSCRIPTION_ID }}
                  ARM_TENANT_ID: ${{ var.ARM_TENANT_ID }}
                  ARM_CLIENT_ID: ${{ var.ARM_CLIENT_ID }}
                  ARM_DEV_CLIENT_ID: ${{ var.ARM_DEV_CLIENT_ID }}
                  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
                  ARM_DEV_CLIENT_SECRET: ${{ secrets.ARM_DEV_CLIENT_SECRET }}
                  TF_VAR_application_name: ${{ env.APPLICATION_NAME }}
                  TF_VAR_environment_name: ${{ env.ENVIRONMENT_NAME }}
                  BACKEND_RESOURCE_GROUP: ${{ var.BACKEND_RESOURCE_GROUP }}
                  BACKEND_STORAGE_ACCOUNT: ${{ var.BACKEND_STORAGE_ACCOUNT }}
                  BACKEND_STORAGE_CONTAINER_NAME: ${{ var.BACKEND_STORAGE_CONTAINER_NAME }}
                  TF_BACKEND_KEY: ${{ env.APPLICATION_NAME }}-${{ env.ENVIRONMENT_NAME }}
                run: |
                   terraform init \
                   -backend-config="resource_group_name=${BACKEND_RESOURCE_GROUP}" \
                   -backend-config="storage_account_name=${BACKEND_STORAGE_ACCOUNT}" \
                   -backend-config="container_name=${BACKEND_STORAGE_CONTAINER_NAME}" \
                   -backend-config="key=${TF_BACKEND_KEY}"

                   terraform apply -auto-approve
